### PR TITLE
Add some new macros and update existing ones

### PR DESCRIPTION
**Pull request by Mathman2028**
This pull request adds a macro for logarithms, along with JSON support. It also adds an optional seed argument for rand, and makes the error message actually show up for error.

### CODE REVIEW

**Review by balt-dev — CHANGES_REQUESTED** [review]
you should _probably_ implement proper error handling for malformed JSON

**Comment by Mathman2028** [comment]
> you should _probably_ implement proper error handling for malformed JSON

what do you mean by that? catch the json error and then just throw another?

**Comment by Mathman2028** [comment]
JSONDecodeError is raised by default when the JSON decoder sees malformed JSON, and I don't see why that can't just be caught like normal.

**Comment by Mathman2028** [comment]
can you be more specific on how you want the error handling changed?

**Comment by balt-dev** [comment]
ah, i see
fair enough

**Review by balt-dev — APPROVED** [review]

**Pull request merged**
