### PR TITLE
Fix event json

### PR DESCRIPTION
**Pull request by Mathman2028**
Tilings are now strings

It looks like that because I did it using a script

### CODE REVIEW

**Comment by Mathman2028** [comment]
Any plans to add this?

**Review by balt-dev — CHANGES_REQUESTED** [review]
can you put the macro changes in a separate pr

**Comment by Mathman2028** [comment]
Okay I think I figured this out

**Comment by Mathman2028** [comment]
> can you put the macro changes in a separate pr

I removed them from this PR, when this goes through I'll work on the macro one
Is this good now?

**Review by balt-dev — APPROVED** [review]

**Pull request merged**
