### PR TITLE
hiragana + sarah + jehjeh + deadke

### PR DESCRIPTION
**Pull request by xbox0**
multiple changes

### CODE REVIEW

**Comment by xbox0** [comment]
30% of hiragana is there now

**Comment by balt-dev** [comment]
> 30% of hiragana is there now

is this ready to merge?

**Comment by balt-dev** [comment]
that's a resounding no

**Comment by someone1065** [comment]
It's a misplaced comma.

**Comment by someone1065** [comment]
To fix, swap lines 28 and 64 in bushy-sprites.

**Pull request merged**
