### PR TITLE
I'm so sorry balt

### PR DESCRIPTION
**Pull request by BockyBlock**
I accidentally overwrote a bunch of words when I added C. Dogs mod, so I fixed it, but as a result I won't be able to add Dogs mod

### CODE REVIEW

**Comment by BockyBlock** [comment]
I wish Gabey didn't tell me to add it, especially knowing that it was mostly RiC-made

**Comment by gabeyk9** [comment]
~~I literally said the property groups what do you want from me~~

**Comment by BockyBlock** [comment]
Sorry, I may have misread

**Comment by gabeyk9** [comment]
Oh whatever, it's fine

**Pull request merged**
