### PR TITLE
Messing with =char

### PR DESCRIPTION
**Pull request by gabeyk9**
balt please tell me if something goes wrong and ill try to fix it

### CODE REVIEW

**Comment by balt-dev** [comment]
oh boy i uh. @gabeyk9 can you test this locally before merging

**Comment by gabeyk9** [comment]
i can do that except i have no idea how to

**Comment by balt-dev** [comment]
basically you're gonna need to
1. install python 3.11 or later
2. make a discord bot over at https://discord.com/developers/applications
3. open, say, your Documents folder or smth
4. `git clone https://github.com/balt-dev/robot-is-chill.git robot-is-chill`
5. `cd robot-is-chill`
6. `pip install -r dependencies.txt`
7. put the token from the second step in `auth.py`
8. `python ROBOT.py`
if this doesn't work contact me on discord

**Comment by gabeyk9** [comment]
Uhh where is auth.py
(also it's requirements not dependencies but that's easily fixed)

**Comment by balt-dev** [comment]
you make it
for example, 
```py
token = "AAAAAAAAAAAAAAAAAAAAAAAA.BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"
```

**Comment by balt-dev** [comment]
> Uhh where is auth.py (also it's requirements not dependencies but that's easily fixed)

ah i'm dumb

**Comment by gabeyk9** [comment]
??? what
image

**Comment by gabeyk9** [comment]
okay now this is broken
image

**Comment by balt-dev** [comment]
ah right! i forgot
you need to make a file called `webhooks.py` with two webhook ids for `logging_id` and `error_id` respectively

**Comment by gabeyk9** [comment]
what does that mean
i'm sorry but this is my first time doing anything like this

**Comment by balt-dev** [comment]
alright

**Pull request merged**
