### PR TITLE
Changing fi again

### PR DESCRIPTION
**Pull request by someone1065**
The other tile I added is nowhere close to finished by the way.

### CODE REVIEW

**Comment by Mathman2028** [comment]
Can you add fianim and fidir to this?

**Comment by someone1065** [comment]
Is this correct?

**Comment by Mathman2028** [comment]
Not sure why you shuffled around the sprites in the json but it seems okay

**Comment by someone1065** [comment]
Yeah I did that so the order in the json matches the order in github.

**Pull request merged**
