### PR TITLE
indev parity changes (mover anim style changes and freeze cell) + more cells (freeze cell, cellba, and cellfo)

### PR DESCRIPTION
**Pull request by Clicktuck-Suskriberz**
this is exactly what it says on the tin

### CODE REVIEW

**Comment by Mathman2028** [comment]
don't rename bread to breadcell, rename it to breader

**Comment by balt-dev** [comment]
hah

**Comment by Clicktuck-Suskriberz** [comment]
the reason why its breadcell is because someone at one point mentioned that a proper bread tile could be added in the future and I didn't wanna interfere with that or cause confusion

**Comment by Mathman2028** [comment]
yeah but all of the others end with -er like mover, pusher, and slider

**Comment by Clicktuck-Suskriberz** [comment]
-strange
-enemy
-immobile
-directional
-freeze (cell)
-cellke
besides in the CM mod it comes from the bread cell is literally just called "bread"

**Comment by someone1065** [comment]
What will happen to the push cell once we add the pusher cell? Is it going to be renamed properly?

**Comment by Mathman2028** [comment]
and all of those should be renamed as well

**Comment by someone1065** [comment]
Renamed to what? Add "cell" at the end of each of them?

**Comment by someone1065** [comment]
Honesty, out of that list, other than strange it all seems perfect as is.

**Comment by someone1065** [comment]
The part that actually needs to be fixed is the mixup between push and pusher, those are two different cells.

**Comment by Clicktuck-Suskriberz** [comment]
whats pusher

**Comment by Mathman2028** [comment]
Renamed to end with "er"

**Comment by Clicktuck-Suskriberz** [comment]
but there's currently only the
_____
|  --  |
|_--__|
pusher in RiC
is there another pusher I should know about?

**Comment by someone1065** [comment]
That's not pusher, that's push, and it's named wrong.

**Comment by Clicktuck-Suskriberz** [comment]
that's balt's fault, not mine
remember, balt made the original sprites for the original cells (and trash, which is usually included in the original cells despite not being in the original game)
I later made every other cell that's in RiC except teleporter
I forget who made teleporter

**Comment by balt-dev** [comment]
is everything in order for me to merge or is there more naming concerns that need bikeshedding

**Comment by Clicktuck-Suskriberz** [comment]
it should be good to merge

**Comment by balt-dev** [comment]
awesome

**Pull request merged**
