### PR TITLE
a bunch of stuff

### PR DESCRIPTION
**Pull request by gabeyk9**
idk how else to describe it
- 2s for every other tiling type
- :clip variant: crops the tile to the 24x24 grid space it's in
- \# prefix for glyphs and =glyph command

### CODE REVIEW

**Comment by gabeyk9** [comment]
?????? what

**Comment by gabeyk9** [comment]
stupid markdown

**Comment by gabeyk9** [comment]
why did it even do that? it's not at the start

**Comment by gabeyk9** [comment]
i still don't know why it applied the bullet points _and then also the markdown_

**Comment by gabeyk9** [comment]
testing...
- baba is you
# baba is you
- # baba is you

**Review by CenTdemeern1 — CHANGES_REQUESTED** [review]
Not too happy with a lot of this. Also, what's with all of the random formatting changes?
Some of the formatting was weird initially, I agree, but a bunch of it didn't need to change

**Comment by gabeyk9** [comment]
i don't want to touch this with a 40 foot pole so i'm just going to close it and deal with it later

**Pull request closed without merging**
