### PR TITLE
Add the basbii collection and also fix a stupid bug with meta that i was 100% sure i tried and also needed 1 line to fix...

### PR DESCRIPTION
**Pull request by gabeyk9**
my description here

### CODE REVIEW

**Comment by gabeyk9** [comment]
i seriously have no idea  how i missed that, it's so dumb

**Comment by balt-dev** [comment]
can you give a reproduction of the bug? now i'm curious

**Comment by gabeyk9** [comment]
...i forgot to set a lower bound.

**Comment by gabeyk9** [comment]
i also set an upper bound; it's 10 but you can increase it if you'd like

**Pull request merged**
