### PR TITLE
A sprite pull

### PR DESCRIPTION
**Pull request by someone1065**
Fi has been expanded to 360x360, the largest currently supported sprite size in order to not have to later shift everything in case more colors are added. Also added another custom character.

### CODE REVIEW

**Comment by balt-dev** [comment]
what exactly is fi anyways

**Comment by Mathman2028** [comment]
> what exactly is fi anyways

it's a tile for making custom tiles using filterimages

**Comment by someone1065** [comment]
^

**Comment by balt-dev** [comment]
ahh i see

**Pull request merged**
