### PR TITLE
Compression macros

### PR DESCRIPTION
**Pull request by DogeisCut**
Macros that make compressing text and data much easier, could be very useful for large macros.

The macros added are:
**[base64.encode/\<string>]
[base64.decode/\<base64 string>]
[zlib.compress/\<string>]
[zlib.decompress/\<base64 string>]**

The zlib macros automatically convert from and to base64.

<sub>Also, I didn't test this, my knowledge on the bot structure is zero to none, and my python isn't the best so, please let me know if I horribly messed this up...<sub>

### CODE REVIEW

**Comment by balt-dev** [comment]
mind uh. testing them first? all you really need to do is put the function definitions into a python interpreter and then give them some values

**Comment by DogeisCut** [comment]
Fair, just tested them and they appear to work as expected.
image

**Comment by balt-dev** [comment]
hopefully nobody zip bombs the bot lmao

**Comment by FofoFromBaba** [comment]
you just know someone's gonna try it now

**Comment by balt-dev** [comment]
the `=blacklist add` in question:

**Pull request merged**
