### PR TITLE
Fix a few sprites.

### PR DESCRIPTION
**Pull request by someone1065**

### CODE REVIEW

**Review by balt-dev — CHANGES_REQUESTED** [review]
what's up with "sub" in constants.py

**Comment by someone1065** [comment]
Yeah I forgot to add that in #120.

**Comment by balt-dev** [comment]
i'm waiting on the changes for constants.py to be removed from the pr to pull it
i've said this before, i'm no longer allowing mixing _any_ code changes with _any_ sprite changes, no matter how small

**Comment by someone1065** [comment]
I don't know how to do that.

**Comment by someone1065** [comment]
Also wasn't this before that rule got added?

**Comment by someone1065** [comment]
Did I do it right?

**Comment by balt-dev** [comment]
yeah, that's fine

**Review by balt-dev — APPROVED** [review]

**Pull request merged**
