### PR TITLE
my last code pull for a while

### PR DESCRIPTION
**Pull request by gabeyk9**
[\*] fixed croppoly + snippoly's operands could not be broadcast with shapes error
[\*] fixed rotation being off center
[+] new pointfill variant, floodfills from a point rather than inside/outside only
[+] new omni variant, makes it like pivot/branching text (nameless)
[-] removed teshobrine

### CODE REVIEW

**Comment by someone1065** [comment]
Minceraft

**Comment by gabeyk9** [comment]
if anyone has any requests, this is close to the last time i'm taking them

**Comment by gabeyk9** [comment]
[+] added $! which lets you get the command in macros (can be t, r, or x)
[+] replace variant (remove but           replaces it      instead of          removing it)

**Comment by balt-dev** [comment]
fuck it, we ball

**Pull request merged**
