### PR TITLE
Pass CI

### PR DESCRIPTION
**Pull request by balt-dev**

### CODE REVIEW

**Review by CenTdemeern1 — CHANGES_REQUESTED** [review]
Why are you mixing tile changes and script changes

**Comment by balt-dev** [comment]
the CI script was incorrectly rejecting some tiles (e.g. rejecting diagtile things)

**Comment by balt-dev** [comment]
also i went and undid the stylistic script changes

**Comment by balt-dev** [comment]
closing for now as it no longer passes CI

**Pull request closed without merging**
