### PR TITLE
Add Dibog

### PR DESCRIPTION
**Pull request by Xavier-says-hi**
Small Debug

### CODE REVIEW

**Comment by FofoFromBaba** [comment]
why does this man have an outline

**Comment by Xavier-says-hi** [comment]
oh dang I need to fix that

**Comment by Xavier-says-hi** [comment]
done

**Comment by balt-dev** [comment]
you missed a comma in the JSON file

**Comment by Xavier-says-hi** [comment]
ok

**Comment by Xavier-says-hi** [comment]
you can use the github channel as a chatroom :nom:

**Comment by balt-dev** [comment]
please don't.

**Comment by someone1065** [comment]
We have discord for that, just make a thread at the pull request message.

**Comment by someone1065** [comment]
Here: https://discord.com/channels/842220825226379265/1244094605570609233

**Comment by someone1065** [comment]
Also every message here creates an embed so I'm probably not going to say anything in this pr anymore not to flood it.

**Pull request merged**
